<?php

namespace Drupal\Tests\bioland\Unit;

use PHPUnit\Framework\TestCase;

/**
 * Guards the BL-1312 embed form display convergence.
 *
 * @group bioland
 * @coversNothing
 */
class BiolandEmbedFormDisplaysTest extends TestCase {

  /**
   * {@inheritdoc}
   */
  public static function setUpBeforeClass(): void {
    parent::setUpBeforeClass();
    require_once __DIR__ . '/../../includes/bioland.install.editor.inc';
  }

  /**
   * {@inheritdoc}
   */
  protected function tearDown(): void {
    \Drupal::resetContainer();
    parent::tearDown();
  }

  /**
   * Builds a form display double.
   */
  private function display(array $components): object {
    return new class($components) {
      public int $saves = 0;

      public function __construct(public array $components) {}

      public function getComponent($name) {
        return $this->components[$name] ?? NULL;
      }

      public function removeComponent($name) {
        unset($this->components[$name]);
        return $this;
      }

      public function setComponent($name, array $options = []) {
        $this->components[$name] = $options;
        return $this;
      }

      public function save() {
        $this->saves++;
      }
    };
  }

  /**
   * Registers the site and returns the displays keyed by mode.
   *
   * @param array<string, object|null> $displays
   *   Stored displays keyed by mode; NULL means not stored yet.
   *
   * @return \ArrayObject
   *   The displays the storage created, keyed by mode.
   */
  private function site(array $displays, ?string $plugin = 'inline_frame', array $modules = ['media_iframe', 'media_library'], string $field = 'field_media_inline_frame'): \ArrayObject {
    $created = new \ArrayObject();
    $storage = new class($displays, $created) {
      public function __construct(private array $displays, private \ArrayObject $created) {}

      public function load($id) {
        return $this->displays[substr($id, strlen('media.embed.'))] ?? NULL;
      }

      public function create(array $values) {
        $display = $this->created[$values['mode']] ?? NULL;
        return $display ?? $this->created[$values['mode']] = new class {
          public int $saves = 0;

          public array $components = [];

          public function getComponent($name) {
            return $this->components[$name] ?? NULL;
          }

          public function removeComponent($name) {
            unset($this->components[$name]);
            return $this;
          }

          public function setComponent($name, array $options = []) {
            $this->components[$name] = $options;
            return $this;
          }

          public function save() {
            $this->saves++;
          }
        };
      }
    };
    $source = new class($plugin, $field) {
      public function __construct(private ?string $plugin, private string $field) {}

      public function getPluginId() {
        return $this->plugin;
      }

      public function getConfiguration() {
        return ['source_field' => $this->field];
      }
    };
    $type = $plugin === NULL ? NULL : new class($source) {
      public function __construct(private object $source) {}

      public function getSource() {
        return $this->source;
      }
    };
    $types = new class($type) {
      public function __construct(private ?object $type) {}

      public function load($id) {
        return $this->type;
      }
    };
    \Drupal::setService('entity_type.manager', new class($storage, $types) {
      public function __construct(private object $storage, private object $types) {}

      public function getStorage($entity_type_id) {
        return $entity_type_id === 'media_type' ? $this->types : $this->storage;
      }
    });
    \Drupal::setService('module_handler', new class($modules) {
      public function __construct(private array $modules) {}

      public function moduleExists($name) {
        return in_array($name, $this->modules, TRUE);
      }
    });
    return $created;
  }

  /**
   * The component the hook is expected to write.
   */
  private function widget(int $weight, array $extra_settings = []): array {
    return [
      'type' => 'iframe_urlwidthheight',
      'weight' => $weight,
      'region' => 'content',
      'settings' => BIOLAND_EMBED_WIDGET_SETTINGS + $extra_settings,
      'third_party_settings' => [],
    ];
  }

  /**
   * Auto-generated displays get the widget defaults; media_library is laid out.
   */
  public function testConvergesAutoGeneratedDisplays(): void {
    $default = $this->display([
      'name' => ['type' => 'string_textfield', 'weight' => -5],
      'created' => ['type' => 'datetime_timestamp'],
      'field_media_inline_frame' => ['type' => 'iframe_urlwidthheight', 'weight' => 0, 'region' => 'content', 'settings' => ['width' => '', 'height' => ''], 'third_party_settings' => []],
    ]);
    $library = $this->display([
      'created' => ['type' => 'datetime_timestamp'],
      'langcode' => ['type' => 'language_select'],
      'path' => ['type' => 'path'],
      'status' => ['type' => 'boolean_checkbox'],
      'uid' => ['type' => 'entity_reference_autocomplete'],
    ]);
    $this->site(['default' => $default, 'media_library' => $library]);

    $this->assertSame('Configured the embed form displays (default, media_library).', _bioland_configure_embed_form_displays());

    $this->assertEquals($this->widget(0), $default->components['field_media_inline_frame']);
    // The rest of the Default form display is left alone.
    $this->assertArrayHasKey('name', $default->components);
    $this->assertArrayHasKey('created', $default->components);
    $this->assertEquals($this->widget(1), $library->components['field_media_inline_frame']);
    $this->assertSame('string_textfield', $library->components['name']['type']);
    $this->assertSame(0, $library->components['name']['weight']);
    foreach (['created', 'langcode', 'path', 'status', 'uid'] as $hidden) {
      $this->assertArrayNotHasKey($hidden, $library->components);
    }
    $this->assertSame(1, $default->saves);
    $this->assertSame(1, $library->saves);
  }

  /**
   * A stored weight is kept.
   */
  public function testKeepsExistingWeight(): void {
    $default = $this->display(['field_media_inline_frame' => ['type' => 'iframe_urlwidthheight', 'weight' => 7]]);
    $this->site(['default' => $default]);
    _bioland_configure_embed_form_displays();
    $this->assertSame(7, $default->components['field_media_inline_frame']['weight']);
  }

  /**
   * Displays that already match are not saved, whatever the key order.
   */
  public function testIsIdempotentRegardlessOfKeyOrder(): void {
    $reordered = [
      'headerlevel' => '3',
      'class' => 'iframe-responsive',
      'frameborder' => '0',
      'scrolling' => 'auto',
      'transparency' => '1',
      'allowfullscreen' => '1',
      'tokensupport' => '0',
      'width' => '100%',
      'height' => '75%',
      'expose_class' => FALSE,
    ];
    $co = fn (int $weight) => [
      'weight' => $weight,
      'type' => 'iframe_urlwidthheight',
      'settings' => $reordered,
      'region' => 'content',
      'third_party_settings' => [],
    ];
    $default = $this->display(['field_media_inline_frame' => $co(0), 'name' => ['type' => 'string_textfield', 'weight' => -5]]);
    $library = $this->display([
      'field_media_inline_frame' => $co(1),
      'name' => ['type' => 'string_textfield', 'weight' => 0, 'region' => 'content', 'settings' => ['size' => 60, 'placeholder' => ''], 'third_party_settings' => []],
    ]);
    $this->site(['default' => $default, 'media_library' => $library]);

    $this->assertSame('Embed form displays already configured.', _bioland_configure_embed_form_displays());
    $this->assertSame(0, $default->saves);
    $this->assertSame(0, $library->saves);
  }

  /**
   * A second run after a first converging run saves nothing.
   */
  public function testSecondRunSavesNothing(): void {
    $default = $this->display([]);
    $library = $this->display([]);
    $this->site(['default' => $default, 'media_library' => $library]);
    _bioland_configure_embed_form_displays();
    $this->assertSame('Embed form displays already configured.', _bioland_configure_embed_form_displays());
    $this->assertSame(1, $default->saves);
    $this->assertSame(1, $library->saves);
  }

  /**
   * A stored setting that differs is corrected.
   */
  public function testCorrectsDriftedSetting(): void {
    $drift = $this->widget(0);
    $drift['settings']['height'] = '50%';
    $default = $this->display(['field_media_inline_frame' => $drift]);
    $this->site(['default' => $default]);
    $this->assertStringStartsWith('Configured', _bioland_configure_embed_form_displays());
    $this->assertSame('75%', $default->components['field_media_inline_frame']['settings']['height']);
  }

  /**
   * A missing display is created; without media_library only Default runs.
   */
  public function testCreatesMissingDisplays(): void {
    $created = $this->site(['default' => NULL, 'media_library' => NULL]);
    _bioland_configure_embed_form_displays();
    $this->assertEquals($this->widget(0), $created['default']->components['field_media_inline_frame']);
    $this->assertEquals($this->widget(1), $created['media_library']->components['field_media_inline_frame']);

    $created = $this->site(['default' => NULL], 'inline_frame', ['media_iframe']);
    _bioland_configure_embed_form_displays();
    $this->assertSame(['default'], array_keys($created->getArrayCopy()));
  }

  /**
   * Without the inline-frame embed type nothing is saved.
   */
  public function testSkipsWithoutInlineFrameType(): void {
    $cases = [
      'no module' => [[], 'inline_frame'],
      'no type' => [['media_iframe'], NULL],
      'other source' => [['media_iframe'], 'file'],
    ];
    foreach ($cases as $label => [$modules, $plugin]) {
      $default = $this->display([]);
      $this->site(['default' => $default], $plugin, $modules);
      $this->assertStringContainsString('skipped', _bioland_configure_embed_form_displays(), $label);
      $this->assertSame(0, $default->saves, $label);
    }
  }

  /**
   * The frame field name comes from the media type's source configuration.
   */
  public function testUsesConfiguredSourceField(): void {
    $default = $this->display([]);
    $this->site(['default' => $default], 'inline_frame', ['media_iframe'], 'field_media_inline_frame_1');
    _bioland_configure_embed_form_displays();
    $this->assertArrayHasKey('field_media_inline_frame_1', $default->components);
    $this->assertArrayNotHasKey('field_media_inline_frame', $default->components);
  }

  /**
   * The widget defaults are the ticket's values, keys sorted.
   */
  public function testWidgetSettingsConstant(): void {
    $keys = array_keys(BIOLAND_EMBED_WIDGET_SETTINGS);
    $sorted = $keys;
    sort($sorted);
    $this->assertSame($sorted, $keys);
    $this->assertSame('100%', BIOLAND_EMBED_WIDGET_SETTINGS['width']);
    $this->assertSame('75%', BIOLAND_EMBED_WIDGET_SETTINGS['height']);
    $this->assertSame('iframe-responsive', BIOLAND_EMBED_WIDGET_SETTINGS['class']);
    $this->assertFalse(BIOLAND_EMBED_WIDGET_SETTINGS['expose_class']);
  }

  /**
   * The setup and hook 9114 run the helpers; 9114 converges search last.
   */
  public function testWiring(): void {
    $source = file_get_contents(dirname(__DIR__, 2) . '/includes/bioland.install.editor.inc');
    $setup = substr($source, strpos($source, 'function _bioland_setup_embed_media('));
    $setup = substr($setup, 0, strpos($setup, "\n}\n"));
    $hook = substr($source, strpos($source, 'function bioland_update_9114('));
    $hook = substr($hook, 0, strpos($hook, "\n}\n"));
    foreach ([$setup, $hook] as $body) {
      $this->assertStringContainsString('_bioland_configure_embed_form_displays()', $body);
      $this->assertStringContainsString('_bioland_backfill_embed_frame_dimensions()', $body);
      $this->assertStringContainsString('_bioland_configure_embed_media_library_display()', $body);
    }
    $this->assertLessThan(strpos($setup, '_bioland_configure_embed_form_displays()'), strpos($setup, '_bioland_create_embed_media_type()'));
    $this->assertLessThan(strpos($hook, '_bioland_v2_update_search_and_facets_config()'), strrpos($hook, '_bioland_backfill_embed_frame_dimensions()'));
    $this->assertLessThan(strpos($hook, '_bioland_configure_embed_media_library_display()'), strpos($hook, '_bioland_configure_embed_form_displays()'));
  }

}
